// ============================================================================
// ARQUIVO: VoucherMarcaDagua.gs
// A MARCA D'ÁGUA DO CERTIFICADO — embutida, e a razão de estar embutida.
//
// De onde ela veio: do PDF que o próprio sindicato emite, mandado pelo
// usuário em 13/08/2026 (o do ÁTILA/ISABELA). Foi extraída da página,
// convertida para cinza — a marca não tem cor — e reduzida para 620px de
// largura, que é folgado para os 120mm em que ela é impressa.
//
// POR QUE BASE64 NO CÓDIGO, E NÃO UM ARQUIVO NO DRIVE
//
// Duas razões, e a segunda é a que decide:
//
//   1. Eu não tenho acesso ao Drive do sindicato. Depender de alguém subir o
//      arquivo e me passar o ID deixaria o documento sair sem marca d'água
//      até lá — e sair errado é pior que demorar.
//   2. `getAs(MimeType.PDF)` não busca host externo de forma confiável, e um
//      arquivo do Drive some do PDF se as permissões mudarem. Já perdemos a
//      assinatura e o QR por isso. O que está embutido não depende de nada.
//
// O CAMINHO DE SAÍDA ESTÁ ABERTO: basta gravar o ID de um arquivo do Drive
// em ScriptProperties, na chave abaixo, e ele passa a mandar. Serve para
// trocar a marca sem mexer em código — e para quando alguém tiver a arte
// original em resolução maior.
//
// 4,6 KB. Não é peso: é menos que o logo do cabeçalho.
// ============================================================================

var VOUCHER_MARCA_DAGUA_PROP = "VOUCHER_MARCA_DAGUA_FILE_ID";

/** A marca d'água, sempre como data: — Drive quando configurado, embutida
 *  quando não. Nunca devolve URL externa: ela funcionaria na prévia e sumiria
 *  no PDF, que é o defeito mais caro deste módulo. */
function marcaDaguaVoucher_() {
  try {
    var id = PropertiesService.getScriptProperties().getProperty(VOUCHER_MARCA_DAGUA_PROP);
    if (id && typeof imagemDoDriveVoucher_ === "function") {
      var doDrive = imagemDoDriveVoucher_(String(id).trim(),
        "sisgep_marca_dagua_voucher_v1", "Marca d'água do certificado");
      if (doDrive) return doDrive;
    }
  } catch (e) {
    Logger.log("Marca d'água do Drive indisponível, usando a embutida: " + e.message);
  }
  return "data:image/jpeg;base64," + VOUCHER_MARCA_DAGUA_B64_();
}

function VOUCHER_MARCA_DAGUA_B64_() {
  return (
  "/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAkGBwgHBgkIBwgKCgkLDRYPDQwMDRsUFRAWIB0iIiAdHx8kKDQsJCYxJx8fLT0tMTU3" +
  "Ojo6Iys/RD84QzQ5Ojf/wAALCANlAmwBAREA/8QAGgABAAMBAQEAAAAAAAAAAAAAAAIDBAEFB//EAC8QAQACAQIEAwcFAQEBAAAA" +
  "AAABAgMEERIhMVFBYXETIjJCUoGRFDNiobEjQ3L/2gAIAQEAAD8A+4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAACu+alPitz7Qqtq4+Wsz6o/rLfRH5drrPqp+JW0z47+O09pWgAAAAAAAAAAAAAAAAAAAAAADl" +
  "rRWJm07QxZtTa+8V92v9qXHQWYs98fKJ3jtLbjyVyV3rPrHZMAAAAAAAAAAAAAAAAAAAAAActMViZmdohgz5Zy2/jHSFToAO0vbH" +
  "aLV6vQxZIyUi0JgAAAAAAAAAAAAAAAAAAAAAMmsyc4xx6yzAAAu02TgybT0tybgAAAAAAAAAAAAAAAAAAAAAJnaJmekPMvbivNp8" +
  "ZcAAAejitx4628uaYAAAAAAAAAAAAAAAAAAAAAhnnbDefJ5wAAA26Od8W3aV4AAAAAAAAAAAAAAAAAAAAAr1H7N/R54AAA2aL9u3" +
  "q0AAAAAAAAAAAAAAAAAAAAACOSOLHaO8PNAAAG7S14cMb+PNcAAAAAAAAAAAAAAAAAAAAADz9RTgyz2nnCsAAHaVm94rHjL0qxwx" +
  "ER0h0AAAAAAAAAAAAAAAAAAAAAFWox+0py+KOjB0AAHGzSYuGOO3WejSAAAAAAAAAAAAAAAAAAAAAAM+owcfvU+LxjuxzEx1AAac" +
  "Gn32teOXhDWAAAAAAAAAAAAAAAAAAAAAAAry4aZOsbT3hlvpslem1o8lU1mvxRMerhETPSN1tNPkt8u0ebTi09Kc5963muAAAAAA" +
  "AAAAAAAAAAAAAAA6ITmxx1vX8ozqMUfNv9kf1WP+X4P1eP8Al+HY1OKfGY9YSjPjn54TraLdJifR0c2jscNfpj8EREdIiHQAAAAA" +
  "AAAAAAAAAAAAAABXfNSnxW59oU21f0V/Km2fLb5tvRXMzPWZkAA+6dcuSvS0ra6u0fFET/S6mpx26zwz5romJjeJ3AAAAAAAAAAA" +
  "AAAAAAAAAJmIjeZ2hmy6ylZ4aRxWUZM+S/Wdo7QrAAAAHa3tSd6zMNGPV9IvH3hppet43rO6QAAAAAAAAAAAAAAAAAAM+XVVryp7" +
  "09/Biy575LcO+8z+IcrXhjvPjKQAAAAAVtNZ3rMxLVi1XSMkfeGmJi0bxO8eToAAAAAAAAAAAAAAAAAhkyVx13tP2Ys2a2Se1ezN" +
  "lybe7X4pSx04I856pgAAAAACePLbHPuzy7NuLNXJHLlbxhYAAAAAAAAAAAAAAAACnPnjHyjnb/GK1ptO9p3lVlycEeco4KfPPXwX" +
  "AAAAAAAETMTvE7S2YNTFtq35T4T3aAAAAAAAAAAAAAAAAGfUajg92nxeM9mOec7y5MxETMs0b5MnNpdAAAAAAABdTU3rWImItt4y" +
  "3AAAAAAAAAAAAAAACjU5uCOGvxT/AExCjUW6Vj7pYK8Nd56ytAAAAAAAAHqAAAAAAAAAAAAAAAK8+WMdN/mnpDz5mZneZ3kcnozR" +
  "E5MnrLUAAAAAAAAD1AAAAAAAAAAAAAAActaK1mZ6Q87Jecl5tP2jsiK81tsfryQ09ec2+y8AAAAAAAAHqAAAAAAAAAAAAAAAx6vL" +
  "vPBE8o6s4KNRPOIWYo2xx580wB2tLW+Gsz9lsabJPhEesp10k/NeI9ITjSUjra0pRpsX0zP3d/T4voh32OP6K/h32WP6K/g9jj+i" +
  "v4c9ji+iHJ0+Kfl29JRnS456bx90J0ceF5+8IW0uSOm0qrYr160lEAB6gAAAAAAAAAAAAAArzX9njmfHwefM7zvIDNm55Nvs0RG3" +
  "J12tZtO1YmfRbTS5Lddq+q6ulpHxTMra4qV6Vj8JgAAAAjbHS/xVifspvpKz8MzCi+nyU8OKPJUA9QAAAAAAAAAAAAAAYdXfiycM" +
  "dKqQGfabajbzbqabJbr7sebRTTY69fenzWxERG0RER5OgAAAAAAhfHS/xVj1ZsmltG80neO0s8xMTtMbT2HqAAAAAAAAAAAAAAI5" +
  "LxSlrT4Q82ec7z1AFujiPb77eEt4AAAAAAAAjfHXJG1o3ZraSYn3bRMebWAAAAAAAAAAAAAAy6220VrHjzZQBo0Uf9LejYAAAAAA" +
  "AAAAAAAAAAAAAAAAAPP1FuPNae3JWANGi/ct6NgAAAAAAAAAAAAAAAAAAAAAADl7cNJtPhDzOoANGi/ct/8ALYAAAAAAAAAAAAAA" +
  "AAAAAAAAAp1c7YZ8+TCAC7R/vfaW4AAAAAAAAAAAAAAAAAAAAAABm1s+7WPNkABZpp2z18+T0AAAAAAAAAAAAAAAAAAAAAAAGPWz" +
  "79Y7QzgA7SeG9Z7S9OAAAAAAAAAN9vEAAAAAAAAAAAAABh1k/wDb7KQAcenitxY6z3hIAAAAAAAAYtVlmMsxXwjZtAAAAAAAAAAA" +
  "AABh1f78+kKQAcbtHbfFw/TK8AAAAAAAByZ2jeXmWnitNp8ZeoAAAAAAAAAAAAADDq/359IUgAL9HbbJNe8NoAAAAAAACnV34cW3" +
  "1cmF6gAAAAAAAAAAAAAMWs/dj0UAAO0twXi0eEvTid43gAAAAAAABh1V+LLtHSvJS9QAAAAAAAAAAAAAGTXRzrLMAAN2kvxYtp61" +
  "5LgAAAAAABHLf2dJt2ebM7zMz1keoAAAAAAAAAAAAADPrY3x1ntLGAALtLfgybT0tybgAAAAAABk1mTeYpHhzlmHqAAAAAAAAAAA" +
  "AAAr1FeLDaPLd54AAPRw39pji3j4pgAAAAAAje0UrNp6Q861ptabT1lweoAAAAAAAAAADlrRWN7TtDNfVx/5xv5yptnyW+aY9OSH" +
  "Hf6rfl2Ml46Xt+VtNVkife2tDRiz0yco5T2laE842eZaOG0x2lwAAXaTJw34Z6W/1uAAAAAABk1mTefZx4dWYHqAAAAAAAAAACvN" +
  "lrirvPOfCO7DkyWyW3tP2RABp0+omJiuSd48Jaxh1deHLv4WjdSAAD0NPk9pSJnrHKVgAAAAACGXJGOk2/DzpneZmesgPUAAAAAA" +
  "AAAAcvaKVm1ukPOyXtktNrIgADVpMu//ADt4dGpRq68WPeOtWIAAE8GT2eSJ8J5S9GJ35wAAAAAAwajL7S/L4Y6KgHqAAAAAAAAA" +
  "AMmsvzikT05yzAAAVmYmJiecPSx246RbvDsxvExPSXm3rwXms+DgAANWky/+dvs1AAAAADNq8u0cFZ5z1ZAB6gAAAAAAAAADzctu" +
  "LJa3eUQAAGzRW3pNe0tDLrMfS8eksoAAETMTvHWHoYMsZKfyjqsAAAABXnyxipv4z0h58zNpmZ5zIAPUAAAAAAAAABy3SXmAAADR" +
  "ovjtHk2OXrFqzWekvNvWaWms9YcAABLHknHaLQ9DHeMlYtXpKQAAACOS8UrNrdHn5LzkvNp/HZEAHqAAAAAAAAAA5PR5nQAAAadD" +
  "HvXnyaxm1eLirxx1jr6MgAACzBlnFbvE9Yb6zFqxMTvEugAADlrRSs2tO0Q8/NlnLbfpEdIQAAeoAAAAAAAAAA87PXgy2j7oAAAN" +
  "ujrti3+qV4PP1GL2d+Xwz0VgAALdPmnHO086z4N0TFoiYneJ6OgAA5a0UrNrTtEMGbLOW3asdIVgAD1AAAAAAAAAAGbWY5msXjw6" +
  "sgAAJY6Te8VjxejWIrWIjpDoIZKRkrwy8+9Zpaa26w4AAAswZpxTz517N9bReOKs7xLoACGTJXHXe0+nmw5ctstt56eEIAAA9QAA" +
  "AAAAAAAByY3jaWDPinFb+M9JVgADbpsPs44rfFP9LwBVqMMZa8vijowTExMxMbTAAAAniy2xW3jpPWG7HkrkrvWfsmAKc2orj5Rz" +
  "t2Yr2te3Fad5cAAAeoAAAAAAAAAAOXrF6zW0bxLFm09sc7151UgDta2vO1Y3lswYIx7Wtzt/i8ABRqMHtI4q/F/rFMbTtPUAAAdp" +
  "a1LcVZ2ltw6iuTlO0W7d1wje9aRvadmTLqbW5U92O/ioAAAHHqgAAAAAAAAAAKsmnx357bT5KbaS3y2ifVD9Ll/j+XY0mTxmsfdZ" +
  "TSVj47TPovrStI2rEQkAACnPgjJzryt/rFetqTtaNpcAAAF+LV+z5ZZ3jv4pX1nFH/KOXeWe1rWne0zM+bgAAAnixWyz7vTxlsrg" +
  "x1rtwxPnK0AAAAAAAAAAAAAAAAQyY65K7WYM2LJhnnHFXvCr2ld9p5T5pRMT0mHQBGb1jrMIWzVjpEyh7TJb4Y/EEYbW52nZbTHW" +
  "nTdMAAAaMOmm3PJyjt4y11rFY2rG0OgAAAAAAAAAAAAAAAAExvHNlzaSLRPBt6SxX08VnaYmsoeytHS8nBl8Lf2cOb6v7cnHl8bf" +
  "2extPWzsYI8ZmU4x0jpVMAAAE8WG+SeUbR3lsxYK4+fW3eVoAAAAAAAAAAAAAAAAAA5etbxtaImGbJpPHHP2lmvS1J96swi6AAAA" +
  "LKYMl/DaO8tOPTUrzt70rwAAAAAAAAAAAAAAAAAAAJiJjaY3hTfTY7c4iaz5KbaS0b8MxP8ASm2K9etJ/CIDjoFYm3wxM+iyunyW" +
  "+Xb1XU0kfPb8L6YqU+GseqYAAAAAAAAAAAAAAAAAAAAAOTStutYn7K50+Kfk29EZ0uPz/Ln6Sne0H6Sn1Wd/SY+9vy7Gmxdpn7p1" +
  "w469KQnERHSNgAAAAAAAAAAAAAAAAAAAAAAAAAAAAB//2Q=="
  );
}
